apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
        - image: northamerica-northeast2-docker.pkg.dev/project-2edd459c-6e8e-42b5-9dd/sofe3980u/binarycalculator
          name: binarycalculator
          ports:
            - containerPort: 8080
              name: binarycalculator
